[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
counter = "GKnpQhwv2os3k6naVpb4GWkdmohFzoGgv3aCEkweRH6q"
pooler = "DmEwwQX5n6mt2Hgv923xmVLDQpWWcvYmTcm3yJbZ5xRr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/mnt/c/custom/uni/tofd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
